/**
 * qaImportFormatService.ts
 * Pure parsing: Markdown string → ImportResult.
 * No filesystem access — keeping format logic separate from transport
 * so future non-file targets can reuse this module.
 *
 * Tolerances (per spec):
 * - Missing file header → human-authored path; file-level warning added.
 * - schema_version / writer_version mismatch → best-effort; file-level warning added.
 * - Missing per-QA metadata fields → filled with safe defaults.
 * - ## Question / ## Answer capitalisation variations and single-hash headers accepted.
 * - Inline q: / a: delimiters accepted (batch-ingest compat).
 * - Missing --- block separator in single-QA files → treated as one block.
 */

import type { QACreateData } from './qaPairService'
import { SCHEMA_VERSION, WRITER_APP } from './qaExportFormatService'

// ─── public types ─────────────────────────────────────────────────────────────

export interface ImportedQA {
  /** Data ready to pass to createPair(). IDs/timestamps are always regenerated by the caller. */
  data: QACreateData
  /** Per-item anomalies: missing fields, unrecognised values, etc. */
  warnings: string[]
  /** original_id preserved from the file, if present. */
  originalId: string
  /** original_timestamp preserved from the file, if present. */
  originalTimestamp: string
}

export interface ImportResult {
  exportType: 'qa' | 'thread' | 'unknown'
  threadName?: string
  items: ImportedQA[]
  /** File-level anomalies: header absent, version mismatch, etc. */
  fileWarnings: string[]
}

// ─── file-header parsing ──────────────────────────────────────────────────────

interface FileHeader {
  writerApp?: string
  writerVersion?: string
  schemaVersion?: number
  exportedAt?: string
  exportType?: 'qa' | 'thread'
  threadName?: string
}

function parseYamlFrontmatter(text: string): { header: FileHeader | null; body: string } {
  const frontmatterRegex = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/
  const match = text.trim().match(frontmatterRegex)
  if (!match) return { header: null, body: text }

  const raw = match[1]
  const body = match[2] ?? ''
  const header: FileHeader = {}

  for (const line of raw.split('\n')) {
    const m = line.match(/^([\w_]+)\s*:\s*(.*)$/)
    if (!m) continue
    const key = m[1].toLowerCase()
    const value = m[2].trim()
    if (key === 'writer_app') header.writerApp = value
    if (key === 'writer_version') header.writerVersion = value
    if (key === 'schema_version') header.schemaVersion = parseInt(value, 10)
    if (key === 'exported_at') header.exportedAt = value
    if (key === 'export_type') header.exportType = value === 'thread' ? 'thread' : 'qa'
    if (key === 'thread_name') header.threadName = value
  }

  return { header, body }
}

// ─── per-block parsing ────────────────────────────────────────────────────────

interface BlockMeta {
  title: string
  source: string
  url: string
  tags: string[]
  version: number
  originalId: string
  originalTimestamp: string
}

function parseBlockMeta(text: string): { meta: BlockMeta; warnings: string[] } {
  const warnings: string[] = []
  const meta: BlockMeta = {
    title: '',
    source: 'manual',
    url: '',
    tags: [],
    version: 0,
    originalId: '',
    originalTimestamp: '',
  }

  // Collect lines before the first ## Question / # Question heading
  const headerBoundary = text.search(/##?\s*question/i)
  const headerSection = headerBoundary >= 0 ? text.substring(0, headerBoundary) : ''

  for (const line of headerSection.split('\n')) {
    const m = line.match(/^([\w_]+)\s*:\s*(.*)$/)
    if (!m) continue
    const key = m[1].toLowerCase()
    const value = m[2].trim()
    if (key === 'title') meta.title = value
    if (key === 'source') meta.source = value || 'manual'
    if (key === 'url') meta.url = value
    if (key === 'tags') {
      meta.tags = value
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean)
    }
    if (key === 'version') meta.version = parseInt(value, 10) || 0
    if (key === 'original_id') meta.originalId = value
    if (key === 'original_timestamp') meta.originalTimestamp = value
  }

  if (!meta.title) warnings.push('title field missing – will be left empty')

  return { meta, warnings }
}

function parseQAContent(text: string): { question: string; answer: string; warnings: string[] } {
  const warnings: string[] = []

  // Try ## Question / ## Answer markdown headings first (deterministic export format)
  const mdQRegex = /##?\s*question\s*\r?\n([\s\S]*?)(?=\n##?\s*answer\b|$)/i
  const mdARegex = /##?\s*answer\s*\r?\n([\s\S]*?)$/i

  const mdQ = text.match(mdQRegex)
  const mdA = text.match(mdARegex)

  if (mdQ || mdA) {
    const question = mdQ ? mdQ[1].trim() : ''
    const answer = mdA ? mdA[1].trim() : ''
    if (!question) warnings.push('question body is empty')
    if (!answer) warnings.push('answer body is empty')
    return { question, answer, warnings }
  }

  // Fallback: q: / a: inline format (matches existing batch-ingest convention)
  const inlineRegex = /q(?:uestion)?\s*:\s*([\s\S]*?)\n+a(?:nswer)?\s*:\s*([\s\S]*)$/i
  const inlineMatch = text.match(inlineRegex)
  if (inlineMatch) {
    const question = inlineMatch[1].trim()
    const answer = inlineMatch[2].trim()
    if (!question) warnings.push('question body is empty')
    if (!answer) warnings.push('answer body is empty')
    return { question, answer, warnings }
  }

  warnings.push('could not detect question/answer structure – check delimiters')
  return { question: '', answer: '', warnings }
}

function parseBlock(blockText: string, blockIndex: number): ImportedQA {
  const { meta, warnings: metaWarnings } = parseBlockMeta(blockText)
  const { question, answer, warnings: contentWarnings } = parseQAContent(blockText)
  const warnings = [...metaWarnings, ...contentWarnings].map((w) => `QA ${blockIndex + 1}: ${w}`)

  return {
    data: {
      title: meta.title,
      source: meta.source,
      url: meta.url,
      tags: meta.tags,
      question,
      answer,
    },
    warnings,
    originalId: meta.originalId,
    originalTimestamp: meta.originalTimestamp,
  }
}

// ─── body splitting ───────────────────────────────────────────────────────────

/**
 * Split export body into individual QA blocks.
 * Blocks are separated by `\n---\n` (Markdown horizontal rule) outside of
 * the per-QA metadata section.  A file with no separator is treated as
 * a single block.
 */
function splitBlocks(body: string): string[] {
  // Split on lines that are exactly `---` (possibly with surrounding whitespace)
  const parts = body.split(/\n[ \t]*---[ \t]*\n/)
  return parts.map((p) => p.trim()).filter((p) => p.length > 0)
}

// ─── public API ───────────────────────────────────────────────────────────────

/** Parse an export Markdown file string into an ImportResult. */
export function parseImportFile(fileContent: string): ImportResult {
  const fileWarnings: string[] = []
  const { header, body } = parseYamlFrontmatter(fileContent)

  // ── file-level validation ──
  if (!header) {
    fileWarnings.push('No file header found – treating as human-authored file')
  } else {
    if (header.writerApp && header.writerApp !== WRITER_APP) {
      fileWarnings.push(`writer_app "${header.writerApp}" is not "${WRITER_APP}" – proceeding best-effort`)
    }
    if (header.schemaVersion !== undefined && header.schemaVersion !== SCHEMA_VERSION) {
      fileWarnings.push(
        `schema_version ${header.schemaVersion} differs from current ${SCHEMA_VERSION} – proceeding best-effort`,
      )
    }
  }

  const exportType = header?.exportType ?? 'unknown'
  const threadName = header?.threadName

  // ── block parsing ──
  const blocks = splitBlocks(body)
  if (blocks.length === 0) {
    fileWarnings.push('No QA blocks found in file')
  }

  const items: ImportedQA[] = blocks.map((block, i) => parseBlock(block, i))

  return { exportType, threadName, items, fileWarnings }
}
